### ISSUE TITLE
Refactor2

### ISSUE THREAD

**Issue by gorobec** [Babiyv/ACB16HW#10]
https://github.com/Babiyv/ACB16HW/blob/dcffd4142c7bcb1cdc0c13c1102772080505c900/_12CheckNumbers.java#L10

Немного улутшил

Scanner sc = new Scanner(System.in);
        System.out.println("Enter number from 100 to 999: ");

        int numb  = sc.nextInt();

        if ( numb < 100 | numb > 999) {
            System.out.println("Invalid number, please check and try again.");
        }

        int a = numb / 100;
        int b = numb % 100 / 10;
        int c = numb % 10;

        if ( a == b & b == c) {
            System.out.println("a): Yes, all figures are equal!");
            System.out.println("b): Yes, all of them are equal");
        } else if (( a == b & b != c ) |
                ( a == c & c != b ) |
                ( b == c & c != a )) {
            System.out.println("a): No, not all figures are equal.");
            System.out.println("b): Yes, two figures are equal");
        } else {
            System.out.println("a): No, not all figures are equal.");
            System.out.println("b): No, there is no equal figures");
        }

**Comment by Babiyv** [comment]
"if ( numb < 100 | numb > 999) " - думал так сделать, но что если
пользователь захочет ввести число "097" к примеру. В принципе оно могло бы
подойти под условие "трехзначного числа".

вт, 27 авг. 2019 г. в 16:20, gorobec <notifications@github.com>:

**Comment by gorobec** [comment]
Да, но нет. 

Система его прочитает как 97. Так что не будем мудрить. Можно конечно сделать и чтобы 0 впереди, но это того не стоит

**Comment by Babiyv** [comment]
окей, просто интересно))

вт, 27 авг. 2019 г. в 17:03, gorobec <notifications@github.com>:
