### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by gorobec** [Babiyv/ACB16HW#11]
https://github.com/Babiyv/ACB16HW/blob/dcffd4142c7bcb1cdc0c13c1102772080505c900/_13Coins.java#L15

Со значениями 11, 12, 13, 14 не сработает

**Comment by Babiyv** [comment]
добавил строку:"

} else if ( coin >= 10 & coin <= 20 ){
    System.out.println( coin + " копеек");
}
"


вт, 27 авг. 2019 г. в 16:23, gorobec <notifications@github.com>:

**Comment by gorobec** [comment]
главное в правильное место добавить)

**Comment by Babiyv** [comment]
все четенько)


вт, 27 авг. 2019 г. в 17:05, gorobec <notifications@github.com>:
