### ISSUE TITLE
От 100000 до 999999 

### ISSUE THREAD

**Issue by gorobec** [Babiyv/ACB16HW#12]
https://github.com/Babiyv/ACB16HW/blob/dcffd4142c7bcb1cdc0c13c1102772080505c900/_14FortuneNumbers.java#L26

 if ( numb < 100000 | numb > 999999 ) {

И эту проверку лучше сделать до того как ты начнешь вычитать цифры, а то программа упадет

**Comment by Babiyv** [comment]
Проверял, не падает Падает только если число превышает максимально
допустимое для инт-а.
Но все равно поправил для оптимизации, спасибо;)

вт, 27 авг. 2019 г. в 16:25, gorobec <notifications@github.com>:
