### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gorobec** [Babiyv/ACB16HW#14]
https://github.com/Babiyv/ACB16HW/blob/dcffd4142c7bcb1cdc0c13c1102772080505c900/_15SquareAndCircle.java#L23

Нужно дорабоать

по первому if:
Нарисуй квадрат и круг, который могут влазить один в другой. 
По сути может быть всего 3 случая, квадрат влазит в круг, круг влазит в квадрат, никто ни в кого не влазит.

последующие проверки можно будет упростить

**Comment by Babiyv** [comment]
Да, тупанул

вт, 27 авг. 2019 г. в 16:48, gorobec <notifications@github.com>:
