### ISSUE TITLE
price > 0

### ISSUE THREAD

**Issue by gorobec** [Babiyv/ACB16HW#8]
https://github.com/Babiyv/ACB16HW/blob/dcffd4142c7bcb1cdc0c13c1102772080505c900/_09DiscountCalc.java#L19

Дополнительную проверку price > 0 уже не надо, предыдущая проверка аналогична этой, и в случае если цена ниже 0, то она попадет в первый блок

**Comment by Babiyv** [comment]
И наверное можно еще убрать:
" else if (price > 1000) {

    System.out.println("Discount is 10% off. Total payment is - " +
(price - (price * 0.1) + "uah."));
}"

и вместо него написать:

" else System.out.println("Discount is 10% off. Total payment is - " +
(price - (price * 0.1) + "uah."));

"

Правильно?


вт, 27 авг. 2019 г. в 16:00, gorobec <notifications@github.com>:

**Comment by gorobec** [comment]
Да, все верно
